name: LRU Cache — tests
on: [push, pull_request]
permissions: { contents: read }
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -U pip pytest
      - run: python -m pytest -q
        env:
          PYTHONDONTWRITEBYTECODE: "1"
